FROM wordpress:cli-php7.4

ENV URL docker03.dest.internal
ENV TITLE test-website
ENV ADMIN_USER joncatlin
ENV ADMIN_PASSWORD password
ENV ADMIN_EMAIL jonc@destini.com

#USER www-data

COPY wp-startup.sh /usr/local/bin/

CMD ["sleep", "555555555555555"]


# TODO
# 1. Remove any installation files that are not needed
