version: '3.1'
# After a lot of playing around the design of this was based on splitting the installation away from 
# the running of wordpress. Tried to combine the web server and wp cli into a single container without success, 
# so resorted to this split design.
services:
  wp-cli-multisite:
    build:
      context: ./wp-cli-multisite
    image: localhost:5000/wp-cli-multisite
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wpdbroot
      WORDPRESS_DB_NAME: wp
    volumes:
      - /mnt/swarm-shared/joncatlin-development/shared-volumes/wordpress-cli/wp:/var/www/html
    networks:
      - wp-net

  wp:
    build:
      context: ./wp
    image: localhost:5000/wp
#    image: wordpress:5.4.2
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wpdbroot
      WORDPRESS_DB_NAME: wp
    volumes:
      - /mnt/swarm-shared/joncatlin-development/shared-volumes/wordpress-cli/wp:/var/www/html
    networks:
      - wp-net

  wp-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: wpdbroot
    volumes:
      - /mnt/swarm-shared/joncatlin-development/shared-volumes/wordpress-cli/db:/var/lib/mysql
    networks:
      - wp-net


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8096:80
    networks:
      - wp-net



networks:
  wp-net:
